name: kcds
channels:
 - conda-forge
 - nodefaults
dependencies:
 - altair-all
 - beautifulsoup4 
 - black
 - blas=*=openblas 
 - bokeh 
 - bottleneck 
 - cloudpickle 
 - cython 
 - dash
 - dash-bootstrap-components
 - dash-core-components
 - dash-html-components
 - dask 
 - dill 
 - flake8
 - flake8-nb
 - h5py 
 - ipympl 
 - ipywidgets 
 - isort
 - jupyter-resource-usage
 - jupyterlab-git 
 - matplotlib
 - numba 
 - numexpr 
 - openpyxl 
 - pandas 
 - panel
 - patsy 
 - protobuf 
 - pytables 
 - pytest
 - python=3.11
 - python-graphviz
 - scikit-image 
 - scikit-learn 
 - scipy 
 - seaborn 
 - sqlalchemy 
 - statsmodels 
 - sympy 
 - vega_datasets
 - widgetsnbextension 
 - xgboost
 - xlrd
