name: r-dssg
channels:
 - conda-forge
 - r 
 - nodefaults
dependencies:
 - jupyter-resource-usage
 - python=3.11
 - r-abind
 - r-backports
 - r-base
 - r-bh
 - r-biocmanager
 - r-boot
 - r-broom
 - r-chron
 - r-class
 - r-classint
 - r-clisymbols
 - r-cluster
 - r-coda
 - r-codetools
 - r-covr
 - r-cowplot
 - r-cpp11
 - r-crosstalk
 - r-cyclocomp
 - r-dbplyr
 - r-deldir
 - r-dichromat
 - r-distributionutils
 - r-dotcall64
 - r-dt
 - r-e1071
 - r-emmeans
 - r-estimability
 - r-feather
 - r-fields
 - r-fnn
 - r-forcats
 - r-foreign
 - r-formatr
 - r-gargle
 - r-generalizedhyperbolic
 - r-geometry
 - r-ggally
 - r-goftest
 - r-gridextra
 - r-gstat
 - r-haven
 - r-hexbin
 - r-highlight
 - r-hunspell
 - r-igraph
 - r-infer
 - r-interp
 - r-intervals
 - r-jpeg
 - r-kernlab
 - r-kernsmooth
 - r-kknn
 - r-lattice
 - r-latticeextra
 - r-lazyeval
 - r-leaflet.providers
 - r-linprog
 - r-lpsolve
 - r-lubridate
 - r-magic
 - r-magick
 - r-manipulatewidget
 - r-markdown
 - r-mass
 - r-matrix
 - r-mclust
 - r-mgcv
 - r-microbenchmark
 - r-misc3d
 - r-mockery
 - r-modelr
 - r-multicool
 - r-mvtnorm
 - r-nlme
 - r-nloptr
 - r-nnet
 - r-parsedate
 - r-pdftools
 - r-pingr
 - r-plot3d
 - r-plotrix
 - r-png
 - r-polyclip
 - r-pool
 - r-pracma
 - r-qpdf
 - r-r.methodss3
 - r-r.oo
 - r-raster
 - r-rcppeigen
 - r-rcppprogress
 - r-readr
 - r-reprex
 - r-rex
 - r-rgdal
 - r-rgl
 - r-rhub
 - r-rjava
 - r-rpart
 - r-rpostgres
 - r-rpostgres
 - r-rpostgresql
 - r-rsolnp
 - r-runit
 - r-rvest
 - r-s2
 - r-sandwich
 - r-selectr
 - r-sf
 - r-shinyjs
 - r-skewhyperbolic
 - r-sp
 - r-spacetime
 - r-spam
 - r-spatial
 - r-spatstat
 - r-spatstat.data
 - r-spatstat.utils
 - r-stringdist
 - r-survival
 - r-systemfonts
 - r-tensor
 - r-tesseract
 - r-testthat
 - r-tidyr
 - r-tidyverse
 - r-tinytest
 - r-tripack
 - r-truncnorm
 - r-units
 - r-uuid
 - r-viridis
 - r-webshot
 - r-whoami
 - r-widgetframe
 - r-wk
 - r-xmlparsedata
