name: Build and publish DSSG image
on: 
  push:
    branches:
      - main
    paths:
      - "r-dssg/Dockerfile"
      - "r-dssg/conda-linux-64.lock"
        
jobs:
    build-publish:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout main
          uses: actions/checkout@v4
          with:
            ref: "main"

        - name: Create release tag
          id: release
          shell: bash
          run: echo "tag=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT

        - name: Build and publish DSSG image
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            name: ubcstatit/r-dssg
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            workdir: "r-dssg"
            tags: "latest,${{ steps.release.outputs.tag }}"
