name: Build and publish STAT 301 images
on:
    push:
      branches:
        - main
      paths:
        - "stat-301/r-stat-301-student/Dockerfile"
        - "stat-301/r-stat-301-student/conda-linux-64.lock"
        - "stat-301/r-stat-301-instructor/Dockerfile"
        
jobs:
    build-publish:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout main
          uses: actions/checkout@v4
          with:
            ref: "main"

        - name: Create release tag
          id: release
          shell: bash
          run: echo "tag=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT

        - name: Build and publish r-stat-301-student image
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            name: ubcstatit/r-stat-301-student
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            workdir: "stat-301/r-stat-301-student"
            tags: "latest,${{ steps.release.outputs.tag }}"

        - name: Build and publish r-stat-301-instructor image
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            name: ubcstatit/r-stat-301-instructor
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            workdir: "stat-301/r-stat-301-instructor"
            tags: "latest,${{ steps.release.outputs.tag }}"
