name: Build and publish KCDS image
on: 
  push:
    branches:
      - main
    paths:
      - "kcds-student/Dockerfile"
      - "kcds-student/conda-linux-64.lock"
      - "kcds-grading/Dockerfile"
        
jobs:
    build-publish:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout main
          uses: actions/checkout@v4
          with:
            ref: "main"

        - name: Create release tag
          id: release
          shell: bash
          run: echo "tag=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT

        - name: Build and publish KCDS student image
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            name: ubcstatit/kcds-student
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            workdir: "kcds-student"
            tags: "latest,${{ steps.release.outputs.tag }}"

        - name: Build and publish KCDS grading image
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            name: ubcstatit/kcds-grading
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            workdir: "kcds-grading"
            tags: "latest,${{ steps.release.outputs.tag }}"